print("Goodbye!", end = "... ")
print("Goodbye!\n\n")
print("No way", end = ".")
print("\nNo\tway.\n\n")
print("    ||   \n    /\   \n \______/\n")
print("*     *\n *   * \n  * *  \n   *   \n  * *  \n *   * \n*     *\n")
print("   *   \n  * *  \n *   * \n* * * *\n")
print("  * *  \n *   * \n  * *  \n")
print("   * * *   \n  *     * \n *       * \n  *     *  \n   * * *   \n")